# Especifica a imagem base
FROM node:18

# Define o diretório de trabalho no contêiner
WORKDIR /usr/src/app

# Copia o arquivo 'package.json' e 'package-lock.json' (se disponível)
COPY package*.json ./

# Instala as dependências do projeto
RUN npm install

# Copia os arquivos do projeto para o diretório de trabalho
COPY . .

# Expõe a porta que o aplicativo usará
EXPOSE 5000

# Comando para rodar o aplicativo
CMD ["node", "app.js"]
